### ISSUE TITLE
Run in 32bit mode

### ISSUE THREAD

**Issue by poplevente** [ciao1092/IELauncher#2]
Is it possible to run it in 32 bit mode somehow?

**Comment by ciao1092** [comment]
Yes, it should be possible to build a 32 bit executable. If you have Visual Studio, you can easily build one yourself, changing the target. If you don't want to install the whole VS, you can try using dotnet build alone, it should work. Otherwise, just comment here and I will upload a 32 bit build when I can.
Please tell me if the issue is solved

**Comment by poplevente** [comment]
great thanks. i will try. yes, i do have VS
